-- 商品列表

INSERT INTO `goods` (`created_at`, `updated_at`, `deleted_at`, `title`, `price`, `original_price`, `discount`, `description`, `param`, `flag`, `status`, `sort`, `num`, `last_snapshot_id`, `user_id`) VALUES ('2023-05-29 19:51:17.000', '2024-03-18 23:08:40.439', NULL, '开发测试的商品', 0.01, 100.00, '活动标签', '这个是描述的信息', '{\"day\":15}', 'shiyongtaocan1', 1, 999, 88, NULL, 1);
INSERT INTO `goods` (`created_at`, `updated_at`, `deleted_at`, `title`, `price`, `original_price`, `discount`, `description`, `param`, `flag`, `status`, `sort`, `num`, `last_snapshot_id`, `user_id`) VALUES ('2023-05-29 19:49:44.000', '2024-03-17 19:55:30.011', NULL, 'PRO-授权30天', 5.00, 0.00, '', '付款成功后立即生效，授权有效期开始计算时间为当天24时', '{\"day\":30}', 'shouquan30days', 1, 44, 88, NULL, 1);
INSERT INTO `goods` (`created_at`, `updated_at`, `deleted_at`, `title`, `price`, `original_price`, `discount`, `description`, `param`, `flag`, `status`, `sort`, `num`, `last_snapshot_id`, `user_id`) VALUES ('2023-05-29 19:49:44.000', '2024-03-18 19:37:45.353', NULL, 'PRO-365天(一年)', 24.00, 48.00, '', '付款成功后立即生效，授权有效期开始计算时间为当天24时', '{\"day\":365}', 'taocan1', 1, 11, 88, NULL, 1);
INSERT INTO `goods` (`created_at`, `updated_at`, `deleted_at`, `title`, `price`, `original_price`, `discount`, `description`, `param`, `flag`, `status`, `sort`, `num`, `last_snapshot_id`, `user_id`) VALUES ('2023-05-29 19:49:44.000', '2024-03-21 11:26:13.357', NULL, 'PRO-永久授权（100年）', 99.00, 0.00, 'PRO 永久钜惠', '<div style=\"font-size:20px\">\n自购买后当天24时算起100年有效期，如果您已经购买了一次，<span style=\"background:#f87171\">请不要多次购买！重新购买会累加至200,300,400....年</span>\n</div>\n<br>\n- 问：为什么不是永久，而是100年？\n<br>\n- 答：这样是为了方便程序计算授权。请不必担心，如果我们可以永生，100年后全部自动授权😉', '{\"day\":36500}', 'taocan1', 1, 1, 88, NULL, 1);
INSERT INTO `goods` (`created_at`, `updated_at`, `deleted_at`, `title`, `price`, `original_price`, `discount`, `description`, `param`, `flag`, `status`, `sort`, `num`, `last_snapshot_id`, `user_id`) VALUES ('2023-05-29 19:49:44.000', '2024-03-18 19:37:45.360', NULL, 'PRO-授权90天', 9.00, 15.00, '', '付款成功后立即生效，授权有效期开始计算时间为当天24时', '{\"day\":90}', 'shouquan30days', 1, 33, 88, NULL, 1);
INSERT INTO `goods` (`created_at`, `updated_at`, `deleted_at`, `title`, `price`, `original_price`, `discount`, `description`, `param`, `flag`, `status`, `sort`, `num`, `last_snapshot_id`, `user_id`) VALUES ('2023-05-29 19:49:44.000', '2024-03-18 19:37:45.366', NULL, 'PRO-授权180天', 15.00, 30.00, '', '付款成功后立即生效，授权有效期开始计算时间为当天24时', '{\"day\":180}', 'shouquan30days', 1, 22, 88, NULL, 1);
INSERT INTO `goods` (`created_at`, `updated_at`, `deleted_at`, `title`, `price`, `original_price`, `discount`, `description`, `param`, `flag`, `status`, `sort`, `num`, `last_snapshot_id`, `user_id`) VALUES ('2023-05-29 19:49:44.000', '2024-03-18 19:37:45.361', NULL, 'PRO-授权2年（730天）', 30.00, 0.00, '', '付款成功后立即生效，授权有效期开始计算时间为当天24时', '{\"day\":730}', 'shouquan30days', 1, 10, 88, NULL, 1);
INSERT INTO `goods` (`created_at`, `updated_at`, `deleted_at`, `title`, `price`, `original_price`, `discount`, `description`, `param`, `flag`, `status`, `sort`, `num`, `last_snapshot_id`, `user_id`) VALUES ('2023-05-29 19:49:44.000', '2024-03-25 12:05:41.378', NULL, 'PRO-授权5年（1900天）', 50.00, 0.00, '5年送75天', '1825(5年)+75(赠送)=1900天。付款成功后立即生效，授权有效期开始计算时间为当天24时', '{\"day\":1900}', 'shouquan30days', 1, 9, 88, NULL, 1);
INSERT INTO `goods` (`created_at`, `updated_at`, `deleted_at`, `title`, `price`, `original_price`, `discount`, `description`, `param`, `flag`, `status`, `sort`, `num`, `last_snapshot_id`, `user_id`) VALUES ('2023-05-29 19:49:44.000', '2024-03-25 12:05:36.978', NULL, 'PRO-授权30天', 1.00, 0.00, '测试期间限时优惠', '付款成功后立即生效，授权有效期开始计算时间为当天24时', '{\"day\":30}', 'shouquan30days', 1, 998, 88, NULL, 1);


-- 系统变量

INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ('system_email', '{\"host\":\"smtp.mxhichina.com\",\"port\":465,\"mail\":\"admin@enianteam.com\",\"password\":\"sjl1996.6.18\"}', NULL);
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ('system_application', '{\"emailSuffix\":\"\",\"openRegister\":true,\"loginCaptcha\":false,\"webSiteUrl\":\"http://120.46.223.120:3912\"}', NULL);
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ('web_about_description', '', NULL);
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ( 'var.logo_url', 'https://lsky.pipuwong.com/jbwmqW.webp', 'logo链接');
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ( 'var.logo_text', 'Sun-Panel授权平台', 'logo文字');
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ( 'var.logo_click_to_link', '/', 'logo点击前往地址');
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ( 'var.system_variable_is_delete', 'false', '允许删除系统变量');
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ( 'var.system_variable_is_edit', 'false', '允许修改系统变量');
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ( 'var.system_variable_is_create', 'true', '允许创建系统变量');
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ( 'var.pro_before_buy_description', '\n购买前须知:\r\n\n为了保证付费用户和作者的权益， 随着版本的升级，激活验证机制，可能会随升级而更新，所以更换新版本可能需要用户手动再次激活（在激活期内的不用再次付费）。\n\n请注意软件目前不支持离线激活，请在有网环境下使用。**标准功能** 无需登录即可使用，使用 **PRO功能** 的功能软件必须要登录。 购买后不支持退款，请谨慎购买，请不要将账号分享给其他用户，如果检测一个账号多个软件激活使用，将收回**PRO权益**，不退款！', 'Pro购买前说明');
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ( 'var.pro_func_description', '<div style=\"color:red;display:flex;justify-content:center\">\n\n\n| 功能                                                                          | 标准版 | Pro版 |\n| ----------------------------------------------------------------------------- | ------ | ----- |\n| <div style=\"color:red;display:flex;justify-content:center\">基础图标管理</div> | ✅     | ✅    |\n| 多账号                                                                        | ✅     | ✅    |\n| 一键切换内外网                                                                | ✅     | ✅    |\n| **系统状态组件**                                                              | ✅     | ✅    |\n| 开放API（开发中）                                                             | ✅     | ✅    |\n| 自定义项目图标（开发中）                                                      | ❌     | ✅    |\n| 自定义登录页的文字（开发中）                                                  | ❌     | ✅    |\n| 在线编写自定义CSS                                                             | ❌     | ✅    |\n| Docker基础管理（开发中）                                                      | ❌     | ✅    |\n| 其他（跟随计划不断开发中）                                                    |        |       |\n\n</div>', 'Pro功能说明');
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ( 'var.donate_reward_description', '亲爱的小伙伴你好，我是 Sun-Panel 的开发者红烧猎人，感谢您一直以来的支持，现推出了Pro功能，对之前用户打赏进行回馈，回馈规则如下：\n\n曾经在 <b><span style=\"color:red\">2024年4月1日前</span></b>   通过以下平台打赏，包括但不仅限于这些平台（支付宝，微信，QQ，B站充电）。请您认真填写以下信息，作者尽量在**24小时内**核对，核对通过后会以邮件的形式下发并通知到您在本平台注册的邮箱。这里有一份 <a target=\"_blank\" style=\"color:blue\" href=\"https://blog.enianteam.com/u/sun/content/259\">打赏名单</a>，未在名单也曾在规定日期打赏过，也可以直接填写以下信息。\n\n| 曾经打赏金额        | 赠送PRO授权时长             | 永久授权                                 |\n| ------------------- | ------------------------ | ---------------------------------------- |\n| 50元以上    | 赠送永久授权（价值99元） |                                          |\n| 30-49元以内 | 10年授权                 | 或加微信（95302870）直接支付30元购买永久 |\n| 10-39元以内 | 5年授权                  | 或加微信（95302870）直接支付50元购买永久 |\n| 1-9元以内   | 2年授权                  | 或加微信（95302870）直接支付60元购买永久 |\n----\n', '捐赠回馈说明');
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ( 'mdPage.test1', '{\"isLogin\":false,\"content\":\"这里是markdown的内容\",\"messageTemplateFlag\":\"default_cn\",\"messageTemplatePosition\":\"top\"}', '测试页面的描述');
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ( 'mdPage.home', '{\"isLogin\":true,\"content\":\"\",\"messageTemplateFlag\":\"2112\",\"messageTemplatePosition\":\"bottom\"}', '首页');
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ( 'mdPage.send_message_cn', '{\"isLogin\":true,\"content\":\"# 发送站内信\",\"messageTemplateFlag\":\"default_cn\",\"messageTemplatePosition\":\"bottom\"}', '通用发站内信页面');
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ( 'var.home_url', '/', '首页地址，登录后跳转等');
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ( 'var.root_page_description', '# 关于Pro版本说明\n\n<div class=\"n-button n-button--default-type n-button--medium-type n-button--color\">啦啦啦啊</div>\n', '跟页面的说明');
INSERT INTO `system_setting` (`config_name`, `config_value`, `description`) VALUES ( 'mdPage.paypal_order_submit_cn', '{\"isLogin\":true,\"content\":\"PayPal的支付方式比较特殊，需要人工审核，所以24小时内才会成功激活，基本信息填写完成请点击保存。\\n\\n\\u003cstyle\\u003e\\nbody,html{\\nbackground:pink;\\n}\\n.dsfjkhadfghd. i{\\nlist-style-type: auto;\\n}\\n\\u003c/style\\u003e\\n\\n基本流程\\n\\n\\u003cdiv style=\\\"list-style-type: auto;\\\" class=\\\"dsfjkhadfghd\\\"\\u003e\\n\\n\\n1.点击下面付款连接进行跳转\\n2.在付款页面进行付款\\n3.付款成功后，将交易号（订单号）复制并回到当前页面粘贴到下面的文本框内\\n4.点击提交，提交后将进行人工审核，24小时内为你开通\\n\\n\\u003c/div\\u003e\\n\\n\",\"messageTemplateFlag\":\"paypal_apply_cn\",\"messageTemplatePosition\":\"bottom\"}', 'Paypal订单提交');

-- 站内信模板

INSERT INTO `sun_pay_test`.`message_template` (`id`, `created_at`, `updated_at`, `deleted_at`, `name`, `flag`, `title`, `title_show`, `title_edit`, `content`, `content_show`, `content_edit`, `note`, `args_json`, `to_usernames`, `to_username_show`, `to_username_edit`, `upload_appendix_show`, `upload_appendix_max`, `upload_appendix_min`, `save_after_url`, `save_button_name`) VALUES (1, '2024-03-12 23:56:38.755', '2024-03-25 19:22:30.100', NULL, 'PayPal支付方式人为激活', 'paypal_apply_cn', 'PayPal支付方式人为激活', 0, 0, '套餐单号：\n{{order}}\nPaypal支付单号：\n{{paypal_order}}\n购买时长（可选：1个月，1个季度，1年，永久）：\n{{duration}}', 0, 0, '', '[{\"keyword\":\"{{paypal_order}}\",\"name\":\"Paypal支付单号\",\"required\":false,\"placeholder\":\"\",\"formType\":\"\"},{\"keyword\":\"{{duration}}\",\"name\":\"购买时长（1个月，1个季度，1年，永久）\",\"required\":false,\"placeholder\":\"\",\"formType\":\"\"},{\"keyword\":\"{{order}}\",\"name\":\"套餐订单号\",\"required\":false,\"placeholder\":\"\",\"formType\":\"\"}]', '95302870@qq.com', 0, 0, 0, 0, 0, '/', '提交');
INSERT INTO `sun_pay_test`.`message_template` (`id`, `created_at`, `updated_at`, `deleted_at`, `name`, `flag`, `title`, `title_show`, `title_edit`, `content`, `content_show`, `content_edit`, `note`, `args_json`, `to_usernames`, `to_username_show`, `to_username_edit`, `upload_appendix_show`, `upload_appendix_max`, `upload_appendix_min`, `save_after_url`, `save_button_name`) VALUES (2, '2024-03-22 10:02:32.526', '2024-03-24 16:44:56.983', NULL, '赞助奖励', 'sponsor_reward_cn', '赞助回馈-用户', 0, 0, '平台：【{{platform}}】\n订单号：【{{order_no}}】\n金额：【{{price}}】', 0, 0, '', '[{\"keyword\":\"{{platform}}\",\"name\":\"打赏平台\",\"required\":true,\"placeholder\":\"示例：支付宝\",\"formType\":\"\"},{\"keyword\":\"{{order_no}}\",\"name\":\"打赏平台的订单号（B站和QQ小伙伴避免冒领填写完信息需要私信我）\",\"required\":true,\"placeholder\":\"必填（b站和QQ填写用户名或者QQ号）\",\"formType\":\"\"},{\"keyword\":\"{{price}}\",\"name\":\"打赏金额\",\"required\":true,\"placeholder\":\"必填并请如实填写\",\"formType\":\"\"}]', '95302870@qq.com', 0, 0, 1, 0, 0, '', '提交');
INSERT INTO `sun_pay_test`.`message_template` (`id`, `created_at`, `updated_at`, `deleted_at`, `name`, `flag`, `title`, `title_show`, `title_edit`, `content`, `content_show`, `content_edit`, `note`, `args_json`, `to_usernames`, `to_username_show`, `to_username_edit`, `upload_appendix_show`, `upload_appendix_max`, `upload_appendix_min`, `save_after_url`, `save_button_name`) VALUES (3, '2024-03-25 12:59:04.153', '2024-03-25 12:59:04.153', NULL, '默认模板', 'default_cn', '', 1, 1, '', 1, 1, '', '[]', '', 1, 1, 1, 5, 0, '/', '发送');

-- 邮件模板

INSERT INTO `email_template` (`created_at`, `updated_at`, `deleted_at`, `name`, `title`, `content`, `note`, `args_json`, `flag`) VALUES ('2024-03-05 18:42:28.000', '2024-03-07 11:32:57.306', NULL, '验证码模板【CN】', '您正在{THING}，需要验证', '<meta charset=\"utf-8\">\n<table width=\"600px\"  style=\"max-width: 600px;\" align=\"center\">\n    <tr style=\"width: 600px;background-color: rgb(28, 197, 249);\">\n        <td align=\"left\" style=\"width: 600px;padding: 22px 18px 11px;display: inline-block;\">\n            <div style=\"font-weight: 900;font-size: 18px;\">\n                <p>Hi {NICKNAME}:</p>\n            </div>\n        </td>\n        <td style=\"width: 100%;display: inline-block;border-top: 4px dashed rgb(255, 255, 255);\"> </td>\n        <td style=\"width: 600px;padding: 18px;display: inline-block;\">\n			<div align=\"left\" style=\"color: rgb(57, 57, 57); line-height: 1.6; font-size: 14px; margin: 0px;font-weight: bolder;\">\n                您正在{THING}，以下是您所需的验证码：\n                <p><div style=\"color: #fff;background-color: #2e2e2e;display: inline-block;padding: 10px 30px;border-radius: 5px;\">{VCODE}</div></p>\n			</div>\n        </td>\n        <td style=\"width: 600px;padding: 18px;display: inline-block;\">\n            <div align=\"rignt\">\n                <div style=\"font-size: 14px; margin: 0px;text-align: right;font-size: 14px; font-weight: bolder;\">\n                    --  来自[<a href=\"{URL}\" style=\"color: #575757;\">Sun-Panel</a>]</div>\n            </div>\n        </td>\n    </tr>\n</table>', '', '[{\"keyword\":\"{THING}\",\"name\":\"注册\"},{\"keyword\":\"{VCODE}\",\"name\":\"验证码\"}]', 'verification_code_cn');
INSERT INTO `email_template` (`created_at`, `updated_at`, `deleted_at`, `name`, `title`, `content`, `note`, `args_json`, `flag`) VALUES ('2024-03-05 22:14:09.761', '2024-03-06 12:32:01.645', NULL, '注册站点成功【CN】', '你已成功注册[Sun-Panel]的订阅站', 'Hi，{EMAIL}\n欢迎的加入[Sun-Panel]订阅站，希望在今后的日子里，一直有你陪伴！', '', '[{\"keyword\":\"{EMAIL}\",\"name\":\"邮箱号\"}]', ' register_success_cn');
INSERT INTO `email_template` (`created_at`, `updated_at`, `deleted_at`, `name`, `title`, `content`, `note`, `args_json`, `flag`) VALUES ('2024-03-05 23:52:45.561', '2024-03-06 12:22:53.276', NULL, 'Beta更新说明【CN】', 'Sun-Panel Beta版本更新了{VERSION}', '你好，我的小伙伴：\nSun-Panel更新了一个beta的版本，版本号：{VERSION}，欢迎您前往更新并体验，如果遇到问题和建议欢迎提出Issue，另外我们可以前往社区进行交流！', '', '[{\"keyword\":\"{VERSION}\",\"name\":\"版本号\"}]', 'beta_update_cn');
INSERT INTO `email_template` (`created_at`, `updated_at`, `deleted_at`, `name`, `title`, `content`, `note`, `args_json`, `flag`) VALUES ('2024-03-06 12:55:08.015', '2024-03-06 12:55:08.015', NULL, '通用模板', '--', '<meta charset=\"utf-8\">\n<table width=\"600px\"  style=\"max-width: 600px;\" align=\"center\">\n    <tr style=\"width: 600px;background-color: rgb(28, 197, 249);\">\n        <td align=\"left\" style=\"width: 600px;padding: 22px 18px 11px;display: inline-block;\">\n            <div style=\"font-weight: 900;font-size: 18px;\">\n                <p>Hi {NICKNAME}:</p>\n            </div>\n        </td>\n        <td style=\"width: 100%;display: inline-block;border-top: 4px dashed rgb(255, 255, 255);\"> </td>\n        <td style=\"width: 600px;padding: 18px;display: inline-block;\">\n			<div align=\"left\" style=\"color: rgb(57, 57, 57); line-height: 1.6; font-size: 14px; margin: 0px;font-weight: bolder;\">\n					{CONTENT}\n			</div>\n        </td>\n        <td style=\"width: 600px;padding: 18px;display: inline-block;\">\n            <div align=\"rignt\">\n                <div style=\"font-size: 14px; margin: 0px;text-align: right;font-size: 14px; font-weight: bolder;\">\n                    --  来自[<a href=\"{URL}\" style=\"color: #575757;\">Sun-Panel</a>]</div>\n            </div>\n        </td>\n    </tr>\n</table>', '', '[{\"keyword\":\"{URL}\",\"name\":\"回调地址\"},{\"keyword\":\"{CONTENT}\",\"name\":\"内容\"},{\"keyword\":\"{NICKNAME}\",\"name\":\"昵称\"}]', 'tongyong_cn');
INSERT INTO `email_template` (`created_at`, `updated_at`, `deleted_at`, `name`, `title`, `content`, `note`, `args_json`, `flag`) VALUES ('2024-03-06 21:05:47.007', '2024-03-06 22:29:00.398', NULL, '用户打赏回赠奖励【CN】', '[Sun-Panel] 感谢您曾经的捐赠，现回赠您Pro版本的激活码，有效期时长为{TIME}', '首先感谢您对项目和作者的支持，经过核查，您曾经的捐赠有效，现对您进行回赠Pro功能的激活码。有效期时长为{TIME}，从今天24时开始计算，请前往【平台】登录账号后查看和使用。\n', '', '[{\"keyword\":\"{TIME}\",\"name\":\"3天/月/年/季度/永久\"}]', 'donate_award_cn');
INSERT INTO `email_template` (`created_at`, `updated_at`, `deleted_at`, `name`, `title`, `content`, `note`, `args_json`, `flag`) VALUES ('2024-03-06 21:20:03.673', '2024-03-06 22:28:40.185', NULL, '推广奖励', '感谢您的推广，现回赠您Pro版激活码，有效时长为{TIME}', '感谢您的推广，现回赠您Pro版激活码。有效时长为{TIME}，从今天24时开始计算，请前往【平台】进行查看', '', '[{\"keyword\":\"{TIME}\",\"name\":\"有效时长\"}]', 'promotion_reward_cn');
