services:
  # 微应用商店
  microapp-store:
    image: 'registry.cn-hangzhou.aliyuncs.com/hslr/microapp-store:1.0.0'
    container_name: sun-panel-microapp-store
    volumes:
    - ./store_data:/app/conf
    - ./store_log:/app/runtime/runlog
    ports:
    - 3050:3088
    restart: always


networks:
  default:
    external:
      name: 1panel-network # 1panel 面板