# ======================
# Basic configuration
# ======================
[base]
# Web run port. Default:3002
http_port=3007
# Database driver [mysql/sqlite(Default)]
database_drive=mysql
# Cache driver [redis/memory(Default)]
cache_drive=memory
# Queue driver [redis/memory(Default)]
queue_drive=memory
# 启用定时任务 [true/false]
scheduler_enable=true
# File cache path (Please start with the current path './')
# Warning: The files that have been uploaded after the modification cannot be accessed
source_path=__$PATH__/uploads
; # File cache path.
source_temp_path=./runtime/temp
; 微应用文件保存路径
micro_app_source_path=__$PATH__/micro_app_upload

# ======================
# Mysql database driver
# ======================
[mysql]
host=127.0.0.1
port=3306
username=root
password=root
db_name=sp_microapp_store
wait_timeout=100

# ======================
# sqlite database driver
# ======================
[sqlite]
file_path=__$PATH__/database/database.db

# ======================
# redis database driver
# ======================
[redis]
address=127.0.0.1:6379
password=
prefix=sp_microapp_store:
db=0

# ======================
# Sun-Store 申请和设置
# ======================
[sun_store]
client_id=
client_secret=
api_host=
# 授权端点
auth_endpoint=


# ======================
# Sun-Store webhook config
# ======================
[sun_store_webhook_secret_key]
goods_order=
user=