# ======================
# Basic configuration
# ======================
[base]
# Web run port. Default:3002
http_port=3005
# Database driver [mysql/sqlite(Default)]
database_drive=mysql
# Cache driver [redis/memory(Default)]
cache_drive=memory
# Queue driver [redis/memory(Default)]
queue_drive=memory
# 启用定时任务 [true/false]
scheduler_enable=true
# File cache path (Please start with the current path './')
# Warning: The files that have been uploaded after the modification cannot be accessed
; source_path=__$PATH__/uploads
; # File cache path.
; source_temp_path=./runtime/temp
; # Custom style path.
; # Need v1.3.1+. Below this version or the note drops the code default use './web/custom'
; custom_style_path=__$PATH__/custom
# 客户端心跳处理间隔 [小时]
client_ping_processing_interval=13

# ======================
# Mysql database driver
# ======================
[mysql]
host=127.0.0.1
port=3306
username=root
password=root
db_name=sun_panel_auth
wait_timeout=100

# ======================
# sqlite database driver
# ======================
[sqlite]
file_path=__$PATH__/database/database.db

# ======================
# redis database driver
# ======================
[redis]
address=127.0.0.1:6379
password=
prefix=sun_panel_auth:
db=0

# ======================
# Sun-Store 申请和设置
# ======================
[sun_store]
client_id=
client_secret=
api_host=
# 授权端点
auth_endpoint=


# ======================
# Sun-Store webhook config
# ======================
[sun_store_webhook_secret_key]
goods_order=
user=