# ======================
# Basic configuration
# ======================
[base]
# Web run port. Default:3002
http_port=3007
# Database driver [mysql/sqlite(Default)]
database_drive=mysql
# Cache driver [redis/memory(Default)]
cache_drive=memory
# Queue driver [redis/memory(Default)]
queue_drive=memory
# 启用定时任务 [true/false]
scheduler_enable=true
# File cache path (Please start with the current path './')
# Warning: The files that have been uploaded after the modification cannot be accessed
source_path=__$PATH__/uploads
; # File cache path.
source_temp_path=./runtime/temp
; 微应用文件保存路径
micro_app_source_path=__$PATH__/micro_app_upload

# ======================
# Mysql database driver
# ======================
[mysql]
host=127.0.0.1
port=3306
username=root
password=root
db_name=sp_microapp_store
wait_timeout=100

# ======================
# sqlite database driver
# ======================
[sqlite]
file_path=__$PATH__/database/database.db

# ======================
# redis database driver
# ======================
[redis]
address=127.0.0.1:6379
password=
prefix=sp_microapp_store:
db=0

# ======================
# Sun-Store 申请和设置
# ======================
[sun_store]
client_id=
client_secret=
api_host=
# 授权端点
auth_endpoint=


# ======================
# Security Audit  Platform API Config
# ======================
[security_audit]
# 平台API地址（如果地址是容器要使用http://<容器名>:内部端口）
platform_url=http://microapp-audit-server:8080
# API密钥
api_secret=hYWxxDCCcM5Ma8Mt3h2H0RemTn9bTG6Q
# 请求超时时间（秒）
timeout=60
# 最大文件大小（字节）
max_file_size=10485760
# 允许扫描的文件扩展名（逗号分隔）
allowed_file_exts=.js

# ======================
# Sun-Store webhook config
# ======================
[sun_store_webhook_secret_key]
goods_order=
user=